const efeitos = ['COMP/Sustain',
'COMP/Volume',
'COMP4/Sustain',
'COMP4/Attack',
'COMP4/Volume',
'COMP4/Clipping',
'S-Comp/Threshold',
'S-Comp/Ratio',
'S-Comp/Volume',
'S-Comp/Attack',
'S-Comp/Release',
'S-Comp/Tone',
'S-Comp/Blend',
'Micro Boost/Gain',
'AC Boost/Gain',
'AC Boost/Volume',
'AC Boost/Bass',
'AC Boost/Treble',
'B-Boost/Gain',
'B-Boost/Volume',
'B-Boost/Bass',
'B-Boost/Treble',
'P-Boost/Gain',
'P-Boost/Volume',
'P-Boost/Bass',
'P-Boost/Treble',
'14 Boost/Gain',
'FAT BB/Bass',
'FAT BB/Treble',
'FAT BB/Volume',
'Boost/Gain',
'OD 9/Gain',
'OD 9/Tone',
'OD 9/Volume',
'Yellow OD/Gain',
'Yellow OD/Volume',
'Penesas/Gain',
'Penesas/Tone',
'Penesas/Volume',
'Super OD/Gain',
'Super OD/Tone',
'Super OD/Volume',
'Blues OD/Gain',
'Blues OD/Tone',
'Blues OD/Volume',
'AC Refiner/Shape',
'AC Sim/Body',
'AC Sim/Top',
'AC Sim/Volume',
'T-Wah/Sense',
'T-Wah/Range',
'T-Wah/Q',
'T-Wah/Mix',
'A-WAH/Depth',
'A-WAH/Rate',
'A-WAH/Volume',
'A-WAH/Low',
'A-WAH/Q',
'A-WAH/High',
'Step Filter/Step 1',
'Step Filter/Step 2',
'Step Filter/Step 3',
'Step Filter/Step 4',
'Step Filter/Rate',
'OCTA/Low Oct',
'OCTA/High Oct',
'OCTA/Dry',
'Pitch/Hi Pitch',
'Pitch/Low Pitch',
'Pitch/Dry',
'Pitch/Hi Vol',
'Pitch/Low Vol',
'P-Bend/Hi Pitch',
'P-Bend/Low Pitch',
'P-Bend/Wet',
'P-Bend/Dry',
'P-Bend/Range',
'Hammy/Volume',
'Hammy/Position',
'Harmonizer 1/Mix',
'Harmonizer 2/Mix',
'Ring Mod/Mix',
'Ring Mod/Freq',
'Ring Mod/Fine',
'Ring Mod/Tone',
'Saturate/Saturation',
'Saturate/Mix',
'Saturate/Volume',
'Saturate/High Cut',
'Auto Swell/Attack',
'Hold/Volume',
'Freeze/Volume',
'Freeze/Attack',
'Freeze/Release',
'V-Wah/Range',
'V-Wah/Q',
'V-Wah/Volume',
'V-Wah/Position',
'C-Wah/Range',
'C-Wah/Q',
'C-Wah/Volume',
'C-Wah/Position',
'P-Wah/Range',
'P-Wah/Q',
'P-Wah/Volume',
'P-Wah/Position',
'S-Wah/Range',
'S-Wah/Q',
'S-Wah/Volume',
'S-Wah/Position',
'B-Wah/Range',
'B-Wah/Q',
'B-Wah/Volume',
'B-Wah/Position',
'Hammy/Volume',
'Hammy/Position',
'Green OD/Gain',
'Green OD/Tone',
'Green OD/Volume',
'OD 9/Gain',
'OD 9/Tone',
'OD 9/Volume',
'Yellow OD/Gain',
'Yellow OD/Volume',
'Penesas/Gain',
'Penesas/Tone',
'Penesas/Volume',
'Swarm/Gain',
'Swarm/Tone',
'Swarm/Volume',
'Super OD/Gain',
'Super OD/Tone',
'Super OD/Volume',
'Scream OD/Gain',
'Scream OD/Tone',
'Scream OD/Volume',
'Blues OD/Gain',
'Blues OD/Tone',
'Blues OD/Volume',
'Force/Gain',
'Force/Tone',
'Force/Volume',
'Blues Master/Gain',
'Blues Master/Tone',
'Blues Master/Volume',
'Master OD/Gain',
'Master OD/Volume',
'Master OD/Bass',
'Master OD/Middle',
'Master OD/Treble',
'TaiChi OD/Gain',
'TaiChi OD/Tone',
'TaiChi OD/Volume',
'TaiChi OD/Voice',
'Timmy OD/Gain',
'Timmy OD/Volume',
'Timmy OD/Bass',
'Timmy OD/Treble',
'Precise OD/Gain',
'Precise OD/Tone',
'Precise OD/Volume',
'Precise OD/Attack',
'Precise OD/Gate',
'Empire OD/Gain',
'Empire OD/Tone',
'Empire OD/Volume',
'Lazaro/Sustain',
'Lazaro/Tone',
'Lazaro/Volume',
'Red Haze/Fuzz',
'Red Haze/Volume',
'Sora Fuzz/Fuzz',
'Sora Fuzz/Volume',
'Plustortion/Gain',
'Plustortion/Volume',
'SM Dist/Gain',
'SM Dist/Tone',
'SM Dist/Volume',
'Darktale/Gain',
'Darktale/Filter',
'Darktale/Volume',
'Chief/Gain',
'Chief/Volume',
'Chief/Bass',
'Chief/Middle',
'Chief/Treble',
'Master Dist/Gain',
'Master Dist/Volume',
'Master Dist/Bass',
'Master Dist/Contour',
'Master Dist/Treble',
'La Charger/Gain',
'La Charger/Tone',
'La Charger/Volume',
'Revolt/Gain',
'Revolt/Tone',
'Revolt/Volume',
'Flagman Dist/Gain',
'Flagman Dist/Volume',
'Flagman Dist/Bass',
'Flagman Dist/Treble',
'Flagman Dist/Presence',
'Flagman Dist/Tight',
'Flex OD/Gain',
'Flex OD/Tone',
'Flex OD/Volume',
'Flex OD/Blend',
'Bass OD/Gain',
'Bass OD/Blend',
'Bass OD/Volume',
'Bass OD/Bass',
'Bass OD/Treble',
'Black Bass/Gain',
'Black Bass/Blend',
'Black Bass/Volume',
'Black Bass/Low',
'Black Bass/Lo-mid',
'Black Bass/Hi-mid',
'Black Bass/Treble',
'Bass Hammer/Gain',
'Bass Hammer/Master',
'Bass Hammer/Bass',
'Bass Hammer/Middle',
'Bass Hammer/Mid Freq',
'Bass Hammer/Treble',
'Micro Boost/Gain',
'AC Boost/Gain',
'AC Boost/Volume',
'AC Boost/Bass',
'AC Boost/Treble',
'B-Boost/Gain',
'B-Boost/Volume',
'B-Boost/Bass',
'B-Boost/Treble',
'P-Boost/Gain',
'P-Boost/Volume',
'P-Boost/Bass',
'P-Boost/Treble',
'14 Boost/Gain',
'FAT BB/Bass',
'FAT BB/Treble',
'FAT BB/Volume',
'Boost/Gain',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'Tweedy/Gain',
'Tweedy/Tone',
'Tweedy/Volume',
'Bellman 59N/Gain',
'Bellman 59N/Presence',
'Bellman 59N/Volume',
'Bellman 59N/Bass',
'Bellman 59N/Middle',
'Bellman 59N/Treble',
'Bellman 59B/Gain',
'Bellman 59B/Presence',
'Bellman 59B/Volume',
'Bellman 59B/Bass',
'Bellman 59B/Middle',
'Bellman 59B/Treble',
'Dark Twin/Gain',
'Dark Twin/Volume',
'Dark Twin/Bass',
'Dark Twin/Middle',
'Dark Twin/Treble',
'Dark DLX/Gain',
'Dark DLX/Volume ',
'Dark DLX/Bass',
'Dark DLX/Treble',
'Dark Vibra/Gain',
'Dark Vibra/Volume',
'Dark Vibra/Bass',
'Dark Vibra/Treble',
'Silver Twin/Gain',
'Silver Twin/Volume',
'Silver Twin/Bass',
'Silver Twin/Middle',
'Silver Twin/Treble',
'SUPDual CL/Gain',
'SUPDual CL/Tone',
'SUPDual CL/Volume',
'SUPDual OD/Gain 1',
'SUPDual OD/Tone 1',
'SUPDual OD/Gain 2',
'SUPDual OD/Tone 2',
'SUPDual OD/Volume',
'Foxy 15TB/Gain',
'Foxy 15TB/Tone Cut',
'Foxy 15TB/Volume',
'Foxy 15TB/Bass',
'Foxy 15TB/Treble',
'Foxy 30N/Gain',
'Foxy 30N/Tone Cut',
'Foxy 30N/Volume',
'Foxy 30TB/Gain',
'Foxy 30TB/Tone Cut',
'Foxy 30TB/Volume',
'Foxy 30TB/Bass',
'Foxy 30TB/Treble',
'J-120 CL/Gain',
'J-120 CL/Bass',
'J-120 CL/Middle',
'J-120 CL/Treble',
'Match CL/Gain',
'Match CL/Presence',
'Match CL/Volume',
'Match CL/Bass',
'Match CL/Middle',
'Match CL/Treble',
'Match OD/Gain',
'Match OD/Presence',
'Match OD/Volume',
'Match OD/Bass',
'Match OD/Middle',
'Match OD/Treble',
'L-Star CL/Gain',
'L-Star CL/Presence',
'L-Star CL/Volume',
'L-Star CL/Bass',
'L-Star CL/Middle',
'L-Star CL/Treble',
'L-Star OD/Input',
'L-Star OD/Gain',
'L-Star OD/Presence',
'L-Star OD/Volume',
'L-Star OD/Bass',
'L-Star OD/Middle',
'L-Star OD/Treble',
'BogSV CL/Gain',
'BogSV CL/Presence',
'BogSV CL/Volume',
'BogSV CL/Bass',
'BogSV CL/Treble',
'BogSV OD/Gain',
'BogSV OD/Presence',
'BogSV OD/Volume',
'BogSV OD/Bass',
'BogSV OD/Middle',
'BogSV OD/Treble',
'Bog BlueV/Gain',
'Bog BlueV/Presence',
'Bog BlueV/Volume',
'Bog BlueV/Bass',
'Bog BlueV/Middle',
'Bog BlueV/Treble',
'Bog BlueM/Gain',
'Bog BlueM/Presence',
'Bog BlueM/Volume',
'Bog BlueM/Bass',
'Bog BlueM/Middle',
'Bog BlueM/Treble',
'Bog RedV/Gain',
'Bog RedV/Presence',
'Bog RedV/Volume',
'Bog RedV/Bass',
'Bog RedV/Middle',
'Bog RedV/Treble',
'Bog RedM/Gain',
'Bog RedM/Presence',
'Bog RedM/Volume',
'Bog RedM/Bass',
'Bog RedM/Middle',
'Bog RedM/Treble',
'Z38 CL/Gain',
'Z38 CL/Tone Cut',
'Z38 CL/Volume',
'Z38 CL/Bass',
'Z38 CL/Middle',
'Z38 CL/Treble',
'Z38 OD/Gain',
'Z38 OD/Tone Cut',
'Z38 OD/Volume',
'Z38 OD/Bass',
'Z38 OD/Middle',
'Z38 OD/Treble',
'Knights CL/Gain',
'Knights CL/Volume',
'Knights CL/Bass',
'Knights CL/Middle',
'Knights CL/Treble',
'Knights CL+/Gain',
'Knights CL+/Volume',
'Knights CL+/Bass',
'Knights CL+/Middle',
'Knights CL+/Treble',
'Knights OD/Gain',
'Knights OD/Volume',
'Knights OD/Bass',
'Knights OD/Middle',
'Knights OD/Treble',
'Bad-KT CL/Gain',
'Bad-KT CL/Presence',
'Bad-KT CL/Volume',
'Bad-KT OD/Gain',
'Bad-KT OD/Presence',
'Bad-KT OD/Volume',
'Bad-KT OD/Bass',
'Bad-KT OD/Edge',
'Bad-KT OD/Treble',
'Solo100 CL/Gain',
'Solo100 CL/Presence',
'Solo100 CL/Volume',
'Solo100 CL/Bass',
'Solo100 CL/Middle',
'Solo100 CL/Treble',
'Solo100 OD/Gain',
'Solo100 OD/Presence',
'Solo100 OD/Volume',
'Solo100 OD/Bass',
'Solo100 OD/Middle',
'Solo100 OD/Treble',
'Solo100 LD/Gain',
'Solo100 LD/Presence',
'Solo100 LD/Volume',
'Solo100 LD/Bass',
'Solo100 LD/Middle',
'Solo100 LD/Treble',
'UK 45/Gain',
'UK 45/Presence',
'UK 45/Volume',
'UK 45/Bass',
'UK 45/Middle',
'UK 45/Treble',
'UK 45+/Gain',
'UK 45+/Presence',
'UK 45+/Volume',
'UK 45+/Bass',
'UK 45+/Middle',
'UK 45+/Treble',
'UK 45JP/Gain 1',
'UK 45JP/Presence',
'UK 45JP/Volume',
'UK 45JP/Bass',
'UK 45JP/Middle',
'UK 45JP/Treble',
'UK 45JP/Gain 2',
'UK 50/Gain',
'UK 50/Presence',
'UK 50/Volume',
'UK 50/Bass',
'UK 50/Middle',
'UK 50/Treble',
'UK 50+/Gain',
'UK 50+/Presence',
'UK 50+/Volume',
'UK 50+/Bass',
'UK 50+/Middle',
'UK 50+/Treble',
'UK 50JP/Gain 1',
'UK 50JP/Presence',
'UK 50JP/Volume',
'UK 50JP/Bass',
'UK 50JP/Middle',
'UK 50JP/Treble',
'UK 50JP/Gain 2',
'UK SLP/Gain',
'UK SLP/Presence',
'UK SLP/Volume',
'UK SLP/Bass',
'UK SLP/Middle',
'UK SLP/Treble',
'UK 800/Gain',
'UK 800/Presence',
'UK 800/Volume',
'UK 800/Bass',
'UK 800/Middle',
'UK 800/Treble',
'UK 900/Gain',
'UK 900/Presence',
'UK 900/Volume',
'UK 900/Bass',
'UK 900/Middle',
'UK 900/Treble',
'Flagman 1/Gain',
'Flagman 1/Presence',
'Flagman 1/Volume',
'Flagman 1/Bass',
'Flagman 1/Middle',
'Flagman 1/Treble',
'Flagman 2/Gain',
'Flagman 2/Presence',
'Flagman 2/Volume',
'Flagman 2/Bass',
'Flagman 2/Middle',
'Flagman 2/Treble',
'Flagman+ 1/Gain',
'Flagman+ 1/Presence',
'Flagman+ 1/Volume',
'Flagman+ 1/Bass',
'Flagman+ 1/Middle',
'Flagman+ 1/Treble',
'Flagman+ 2/Gain',
'Flagman+ 2/Presence',
'Flagman+ 2/Volume',
'Flagman+ 2/Bass',
'Flagman+ 2/Middle',
'Flagman+ 2/Treble',
'Mess2C+ 1/Gain',
'Mess2C+ 1/Presence',
'Mess2C+ 1/Volume',
'Mess2C+ 1/Bass',
'Mess2C+ 1/Middle',
'Mess2C+ 1/Treble',
'Mess2C+ 2/Gain',
'Mess2C+ 2/Presence',
'Mess2C+ 2/Volume',
'Mess2C+ 2/Bass',
'Mess2C+ 2/Middle',
'Mess2C+ 2/Treble',
'Mess2C+ 3/Gain',
'Mess2C+ 3/Presence',
'Mess2C+ 3/Volume',
'Mess2C+ 3/Bass',
'Mess2C+ 3/Middle',
'Mess2C+ 3/Treble',
'Mess4 LD/Gain',
'Mess4 LD/Presence',
'Mess4 LD/Volume',
'Mess4 LD/Bass',
'Mess4 LD/Middle',
'Mess4 LD/Treble',
'Mess4 LD 2/Gain',
'Mess4 LD 2/Presence',
'Mess4 LD 2/Volume',
'Mess4 LD 2/Bass',
'Mess4 LD 2/Middle',
'Mess4 LD 2/Treble',
'Mess4 LD 3/Gain',
'Mess4 LD 3/Presence',
'Mess4 LD 3/Volume',
'Mess4 LD 3/Bass',
'Mess4 LD 3/Middle',
'Mess4 LD 3/Treble',
'Mess DualV/Gain',
'Mess DualV/Presence',
'Mess DualV/Volume',
'Mess DualV/Bass',
'Mess DualV/Middle',
'Mess DualV/Treble',
'Mess DualM/Gain',
'Mess DualM/Presence',
'Mess DualM/Volume',
'Mess DualM/Bass',
'Mess DualM/Middle',
'Mess DualM/Treble',
'Juice30 OD/Gain',
'Juice30 OD/Volume',
'Juice30 OD/Bass',
'Juice30 OD/Middle',
'Juice30 OD/Treble',
'Juice R100/Gain',
'Juice R100/Volume',
'Juice R100/Bass',
'Juice R100/Middle',
'Juice R100/Treble',
'EV 51/Gain',
'EV 51/Volume',
'EV 51/Bass',
'EV 51/Middle',
'EV 51/Treble',
'EV 51/Presence',
'Eagle 120/Gain',
'Eagle 120/Presence',
'Eagle 120/Volume',
'Eagle 120/Bass',
'Eagle 120/Middle',
'Eagle 120/Treble',
'Eagle 120+/Gain',
'Eagle 120+/Presence',
'Eagle 120+/Volume',
'Eagle 120+/Bass',
'Eagle 120+/Middle',
'Eagle 120+/Treble',
'Power LD/Gain',
'Power LD/Presence',
'Power LD/Volume',
'Power LD/Bass',
'Power LD/Middle',
'Power LD/Treble',
'Dizz VH/Gain',
'Dizz VH/Presence',
'Dizz VH/Volume',
'Dizz VH/Bass',
'Dizz VH/Middle',
'Dizz VH/Treble',
'Dizz VH S/Gain',
'Dizz VH S/Presence',
'Dizz VH S/Volume',
'Dizz VH S/Bass',
'Dizz VH S/Middle',
'Dizz VH S/Treble',
'Dizz VH+/Gain',
'Dizz VH+/Presence',
'Dizz VH+/Volume',
'Dizz VH+/Bass',
'Dizz VH+/Middle',
'Dizz VH+/Treble',
'Dizz VH+ S/Gain',
'Dizz VH+ S/Presence',
'Dizz VH+ S/Volume',
'Dizz VH+ S/Bass',
'Dizz VH+ S/Middle',
'Dizz VH+ S/Treble',
'Classic Bass/Gain',
'Classic Bass/Bass',
'Classic Bass/Middle',
'Classic Bass/Treble',
'Classic Bass/Volume',
'Foxy Bass/Volume',
'Foxy Bass/Bass',
'Foxy Bass/Treble',
'Mess Bass/Gain',
'Mess Bass/Volume',
'Mess Bass/Bass',
'Mess Bass/Middle',
'Mess Bass/Treble',
'Mini Bass/Volume',
'Mini Bass/Bass',
'Mini Bass/Treble',
'Bass Pre/Volume',
'Bass Pre/Bass',
'Bass Pre/Middle',
'Bass Pre/Treble',
'AC Pre/Volume',
'AC Pre/Tone',
'AC Pre/Balance',
'AC Pre/EQ Freq',
'AC Pre/EQ Q',
'AC Pre/EQ Gain',
'AC Pre 2/Volume',
'AC Pre 2/Tone',
'AC Pre 2/Balance',
'AC Pre 2/EQ Freq',
'AC Pre 2/EQ Q',
'AC Pre 2/EQ Gain',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'SnapTone/Gain',
'SnapTone/Volume',
'SnapTone/Bass',
'SnapTone/Middle',
'SnapTone/Treble',
'Gate 1/Threshold',
'Gate 2/Threshold',
'Gate 2/Attack',
'Gate 2/Release',
'Auto Swell/Attack',
'SUP ZEP/Volume',
'SUP ZEP/Low Cut',
'SUP ZEP/High Cut',
'TWD CP/Volume',
'TWD CP/Low Cut',
'TWD CP/High Cut',
'TWD PRC/Volume',
'TWD PRC/Low Cut',
'TWD PRC/High Cut',
'TWD SUP/Volume',
'TWD SUP/Low Cut',
'TWD SUP/High Cut',
'TWD LUX/Volume',
'TWD LUX/Low Cut',
'TWD LUX/High Cut',
'DARK LUX/Volume',
'DARK LUX/Low Cut',
'DARK LUX/High Cut',
'DARK VIT/Volume',
'DARK VIT/Low Cut',
'DARK VIT/High Cut',
'Dark Twin/Volume',
'Dark Twin/Low Cut',
'Dark Twin/High Cut',
'Dark CS/Volume',
'Dark CS/Low Cut',
'Dark CS/High Cut',
'Bellman 1/Volume',
'Bellman 1/Low Cut',
'Bellman 1/High Cut',
'Bellman 2/Volume',
'Bellman 2/Low Cut',
'Bellman 2/High Cut',
'J-120/Volume',
'J-120/Low Cut',
'J-120/High Cut',
'UK G12/Volume',
'UK G12/Low Cut',
'UK G12/High Cut',
'UK GRN 1/Volume',
'UK GRN 1/Low Cut',
'UK GRN 1/High Cut',
'UK LD/Volume',
'UK LD/Low Cut',
'UK LD/High Cut',
'UK TD/Volume',
'UK TD/Low Cut',
'UK TD/High Cut',
'UK MD/Volume',
'UK MD/Low Cut',
'UK MD/High Cut',
'UK GRN 2/Volume',
'UK GRN 2/Low Cut',
'UK GRN 2/High Cut',
'UK 75/Volume',
'UK 75/Low Cut',
'UK 75/High Cut',
'UK Dark/Volume',
'UK Dark/Low Cut',
'UK Dark/High Cut',
'FOXY 1/Volume',
'FOXY 1/Low Cut',
'FOXY 1/High Cut',
'FOXY 2/Volume',
'FOXY 2/Low Cut',
'FOXY 2/High Cut',
'ROUT/Volume',
'ROUT/Low Cut',
'ROUT/High Cut',
'BogSV/Volume',
'BogSV/Low Cut',
'BogSV/High Cut',
'Bad-KT/Volume',
'Bad-KT/Low Cut',
'Bad-KT/High Cut',
'Match/Volume',
'Match/Low Cut',
'Match/High Cut',
'TOM OPEN/Volume',
'TOM OPEN/Low Cut',
'TOM OPEN/High Cut',
'ACE/Volume',
'ACE/Low Cut',
'ACE/High Cut',
'Mess/Volume',
'Mess/Low Cut',
'Mess/High Cut',
'D STAR/Volume',
'D STAR/Low Cut',
'D STAR/High Cut',
'SUP Star/Volume',
'SUP Star/Low Cut',
'SUP Star/High Cut',
'US STO/Volume',
'US STO/Low Cut',
'US STO/High Cut',
'BOUTI/Volume',
'BOUTI/Low Cut',
'BOUTI/High Cut',
'SUP/Volume',
'SUP/Low Cut',
'SUP/High Cut',
'MATT TWD/Volume',
'MATT TWD/Low Cut',
'MATT TWD/High Cut',
'Freed/Volume',
'Freed/Low Cut',
'Freed/High Cut',
'DB Rock/Volume',
'DB Rock/Low Cut',
'DB Rock/High Cut',
'Blue SK/Volume',
'Blue SK/Low Cut',
'Blue SK/High Cut',
'EV/Volume',
'EV/Low Cut',
'EV/High Cut',
'Bog/Volume',
'Bog/Low Cut',
'Bog/High Cut',
'Eagle/Volume',
'Eagle/Low Cut',
'Eagle/High Cut',
'Uban/Volume',
'Uban/Low Cut',
'Uban/High Cut',
'Solo/Volume',
'Solo/Low Cut',
'Solo/High Cut',
'Juice/Volume',
'Juice/Low Cut',
'Juice/High Cut',
'H-WAY/Volume',
'H-WAY/Low Cut',
'H-WAY/High Cut',
'Way/Volume',
'Way/Low Cut',
'Way/High Cut',
'Dumb/Volume',
'Dumb/Low Cut',
'Dumb/High Cut',
'Dizz/Volume',
'Dizz/Low Cut',
'Dizz/High Cut',
'TRP/Volume',
'TRP/Low Cut',
'TRP/High Cut',
'King/Volume',
'King/Low Cut',
'King/High Cut',
'ADM 1/Volume',
'ADM 1/Low Cut',
'ADM 1/High Cut',
'ADM 2/Volume',
'ADM 2/Low Cut',
'ADM 2/High Cut',
'Workman 1/Volume',
'Workman 1/Low Cut',
'Workman 1/High Cut',
'Workman 2/Volume',
'Workman 2/Low Cut',
'Workman 2/High Cut',
'US BASS/Volume',
'US BASS/Low Cut',
'US BASS/High Cut',
'MATT/Volume',
'MATT/Low Cut',
'MATT/High Cut',
'F-TOP/Volume',
'F-TOP/Low Cut',
'F-TOP/High Cut',
'AMPG 1/Volume',
'AMPG 1/Low Cut',
'AMPG 1/High Cut',
'AMPG 2/Volume',
'AMPG 2/Low Cut',
'AMPG 2/High Cut',
'HACK/Volume',
'HACK/Low Cut',
'HACK/High Cut',
'AC/Volume',
'AC/Low Cut',
'AC/High Cut',
'AC Dream/Volume',
'AC Dream/Low Cut',
'AC Dream/High Cut',
'OM/Volume',
'OM/Low Cut',
'OM/High Cut',
'JUMBO/Volume',
'JUMBO/Low Cut',
'JUMBO/High Cut',
'Bird/Volume',
'Bird/Low Cut',
'Bird/High Cut',
'GA/Volume',
'GA/Low Cut',
'GA/High Cut',
'Classic AC/Volume',
'Classic AC/Low Cut',
'Classic AC/High Cut',
'Mandolin/Volume',
'Mandolin/Low Cut',
'Mandolin/High Cut',
'Fretless Bass/Volume',
'Fretless Bass/Low Cut',
'Fretless Bass/High Cut',
'Double Bass/Volume',
'Double Bass/Low Cut',
'Double Bass/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'User IR/Volume',
'User IR/Low Cut',
'User IR/High Cut',
'G-Chorus/Depth',
'G-Chorus/Rate',
'G-Chorus/Volume',
'B-Chorus/Depth',
'B-Chorus/Rate',
'B-Chorus/Volume',
'M-Chorus/Mix',
'M-Chorus/Rate',
'M-Chorus/Filter',
'M-Chorus/Depth L',
'M-Chorus/Depth C',
'M-Chorus/Depth R',
'Jet/Depth',
'Jet/Rate',
'Jet/Pre Delay',
'Jet/Feedback',
'B-Jet/Depth',
'B-Jet/Rate',
'B-Jet/Pre Delay',
'B-Jet/Feedback',
'N-Jet/Depth',
'N-Jet/Rate',
'N-Jet/Pre Delay',
'N-Jet/Feedback',
'Trem Jet/Flg Depth',
'Trem Jet/Flg Rate',
'Trem Jet/Feedback',
'Trem Jet/Trm Depth',
'Trem Jet/Trm Rate',
'V-Roto/Depth',
'V-Roto/Rate',
'G-Roto/Depth',
'G-Roto/Rate',
'G-Roto/Volume',
'Vibrato/Depth',
'Vibrato/Rate',
'Vibrato/Volume',
'Vibrato T/Sens',
'Vibrato T/Rate',
'Vibrato T/Output',
'O-Phase/Rate',
'G-Phase/Depth',
'G-Phase/Rate',
'S-Phase/Rate',
'Pan Phase/Phs Depth',
'Pan Phase/Phs Rate',
'Pan Phase/Pan Depth',
'Pan Phase/Pan Rate',
'M-Vibe/Depth',
'M-Vibe/Rate',
'Vibe/Depth',
'Vibe/Rate',
'Vibe/Volume',
'O-Trem/Depth',
'O-Trem/Rate',
'Sine Trem/Depth',
'Sine Trem/Rate',
'Sine Trem/Volume',
'Triangle Trem/Depth',
'Triangle Trem/Rate',
'Triangle Trem/Volume',
'Bias Trem/Depth',
'Bias Trem/Rate',
'Bias Trem/Volume',
'Bias Trem/Bias',
'Detune/Detune',
'Detune/Wet',
'Detune/Dry',
'Bit Smash/Mix',
'Bit Smash/Krush',
'Bit Smash/Bit',
'Bit Smash/Hi Cut',
'Bit Smash/Lo Cut',
'Auto Swell/Attack',
'Hold/Volume',
'Freeze/Volume',
'Freeze/Attack',
'Freeze/Release',
'BBD Delay S/Mix',
'BBD Delay S/Time',
'BBD Delay S/Feedback',
'BBD Delay S/Time R%',
'BBD Delay S/Spread',
'BBD Delay S/Level',
'Digital Delay S/Mix',
'Digital Delay S/Time',
'Digital Delay S/Feedback',
'Digital Delay S/Time R%',
'Digital Delay S/Spread',
'Digital Delay S/Level',
'Tape Delay S/Mix',
'Tape Delay S/Time',
'Tape Delay S/Feedback',
'Tape Delay S/Time R%',
'Tape Delay S/Spread',
'Tape Delay S/Wow &',
'Tape Delay S/Scrape',
'Tape Delay S/Drive',
'Tape Delay S/Level',
'Ambience 1/Mix',
'Ambience 1/Time',
'Ambience 1/Feedback',
'Ambience 1/Level',
'Ambience 1/Mod',
'Ambience 1/Tone',
'Ambience 2/Mix',
'Ambience 2/Time',
'Ambience 2/Feedback',
'Ambience 2/Level',
'Ambience 2/Mod',
'Ambience 2/Tone',
'Pure/Mix',
'Pure/Time',
'Pure/Feedback',
'Analog/Mix',
'Analog/Time',
'Analog/Feedback',
'Tape/Mix',
'Tape/Time',
'Tape/Feedback',
'Ping Pong/Mix',
'Ping Pong/Time',
'Ping Pong/Feedback',
'Slapback/Mix',
'Slapback/Time',
'Slapback/Feedback',
'Sweep Echo/Mix',
'Sweep Echo/Time',
'Sweep Echo/Feedback',
'Sweep Echo/Sweep Depth',
'Sweep Echo/Sweep Rate',
'Ring Echo/Dly Mix',
'Ring Echo/Time',
'Ring Echo/Feedback',
'Ring Echo/Ring Mix',
'Ring Echo/Freq',
'Ring Echo/Tone',
'Tube/Mix',
'Tube/Time',
'Tube/Feedback',
'M-Echo/Mix',
'M-Echo/Time',
'M-Echo/Feedback',
'M-Echo/Tone',
'M-Echo/Mode',
'Sweet Echo/Mix',
'Sweet Echo/Time',
'Sweet Echo/Feedback',
'999 Echo/Mix',
'999 Echo/Time',
'999 Echo/Feedback',
'Vintage Rack/Mix',
'Vintage Rack/Time',
'Vintage Rack/Feedback',
'Vintage Rack/Mod',
'Vintage Rack/Tone',
'Lofi Echo/Mix',
'Lofi Echo/Time',
'Lofi Echo/Feedback',
'Lofi Echo/Crush',
'Lofi Echo/Bit',
'Rev Echo/Mix',
'Rev Echo/Time',
'Rev Echo/Feedback',
'Rev Echo/Level',
'Dual Echo/Mix A',
'Dual Echo/Time A',
'Dual Echo/Feedback A',
'Dual Echo/Mix B',
'Dual Echo/Time B',
'Dual Echo/Feedback B',
'Ice Delay/Mix',
'Ice Delay/Time',
'Ice Delay/Feedback',
'Ice Delay/Tone',
'Ice Delay/Mod',
'Ice Delay/Direction',
'Ice Delay/Blend',
'Ice Delay/Smooth',
'Ice Delay/Level',
'Room/Mix',
'Room/Pre Delay',
'Room/Decay',
'Hall/Mix',
'Hall/Pre Delay',
'Hall/Decay',
'Church/Mix',
'Church/Pre Delay',
'Church/Decay',
'Plate/Mix',
'Plate/Decay',
'Plate/High Damp',
'Spring/Mix',
'Spring/Decay',
'Spring/Tone',
'Tube Spring/Mix',
'Tube Spring/Pre Delay',
'Tube Spring/Decay',
'Tube Spring/Low Damp',
'Tube Spring/Hi Damp',
'Tube Spring/Mod',
'Amp Spring/Mix',
'Amp Spring/Pre Delay',
'Amp Spring/Decay',
'Amp Spring/Low Damp',
'Amp Spring/Hi Damp',
'Amp Spring/Mod',
'Studio/Mix',
'Studio/Pre Delay',
'Studio/Decay',
'Studio/Low Damp',
'Studio/Hi Damp',
'Studio/Mod',
'Club/Mix',
'Club/Pre Delay',
'Club/Decay',
'Club/Low Damp',
'Club/Hi Damp',
'Club/Mod',
'Concert/Mix',
'Concert/Pre Delay',
'Concert/Decay',
'Concert/Low Damp',
'Concert/Hi Damp',
'Concert/Mod',
'Arena/Mix',
'Arena/Pre Delay',
'Arena/Decay',
'Arena/Low Damp',
'Arena/Hi Damp',
'Arena/Mod',
'N-Star/Mix',
'N-Star/Decay',
'Deepsea/Mix',
'Deepsea/Decay',
'Sweet Space/Mix',
'Sweet Space/Pre Delay',
'Sweet Space/Decay',
'Sweet Space/Lo End',
'Sweet Space/Hi End',
'Shimmer/Mix',
'Shimmer/Pre Delay',
'Shimmer/Decay',
'Shimmer/Lo End',
'Shimmer/Hi End',
'Volume/Volume'
];
